feat: bump version

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -65,7 +65,16 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
         run: |
-          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
-          -H "Accept: application/vnd.github+json" \
-          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-and-release.yml/dispatches \
-          -d '{"ref":"refs/tags/${{ steps.versions.outputs.current_version }}"}'
+          response=$(curl -s -o /dev/null -w "%{http_code}" \
+            -X POST \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-and-release.yml/dispatches \
+            -d '{"ref":"refs/tags/${{ steps.versions.outputs.current_version }}"}')
+
+          if [[ "$response" -lt 200 || "$response" -ge 400 ]]; then
+            echo "Error triggering workflow dispatch: HTTP $response"
+            exit 1
+          else
+            echo "Workflow dispatch triggered successfully: HTTP $response"
+          fi
